import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  compareBuildVersion,
  isBuildVersion,
  setBuildVersionContents,
} from "../../scripts/set-build-version.mjs";

const scriptPath = resolve(process.cwd(), "scripts/set-build-version.mjs");

function fixtureFiles(version = "0.0.24", packageName = "clovy") {
  return {
    tauriConf: `{\n  "version": "${version}"\n}\n`,
    cargoToml: `[package]\nname = "${packageName}"\nversion = "${version}"\nedition = "2021"\n`,
    cargoLock: `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "${packageName}"\nversion = "${version}"\n`,
    packageJson: `{\n  "version": "${version}"\n}\n`,
  };
}

function writeFixture(version = "0.0.24", packageName = "clovy") {
  const root = mkdtempSync(join(tmpdir(), "clovy-version-"));
  const files = fixtureFiles(version, packageName);
  mkdirSync(join(root, "src-tauri", "src"), { recursive: true });
  writeFileSync(join(root, "package.json"), files.packageJson);
  writeFileSync(join(root, "src-tauri", "tauri.conf.json"), files.tauriConf);
  writeFileSync(join(root, "src-tauri", "Cargo.toml"), files.cargoToml);
  writeFileSync(join(root, "src-tauri", "Cargo.lock"), files.cargoLock);
  writeFileSync(join(root, "src-tauri", "src", "lib.rs"), "");
  return { root, files };
}

function readFixture(root) {
  return {
    packageJson: readFileSync(join(root, "package.json"), "utf8"),
    tauriConf: readFileSync(join(root, "src-tauri", "tauri.conf.json"), "utf8"),
    cargoToml: readFileSync(join(root, "src-tauri", "Cargo.toml"), "utf8"),
    cargoLock: readFileSync(join(root, "src-tauri", "Cargo.lock"), "utf8"),
  };
}

describe("isBuildVersion", () => {
  it("accepts plain releases and rc prereleases", () => {
    for (const version of ["0.0.25", "1.2.3", "0.0.25-rc.1", "1.2.3-rc.10"]) {
      expect(isBuildVersion(version)).toBe(true);
    }
  });

  it("rejects malformed or non-rc prerelease versions", () => {
    // dangling -rc, wrong channel, leading-zero rc number, partial semver,
    // v-prefix, trailing junk, empty — none may stamp an artifact version.
    for (const version of [
      "0.0.25-rc",
      "0.0.25-beta.1",
      "0.0.25-rc.01",
      "1.2",
      "v1.2.3",
      "0.0.25-rc.1-extra",
      "",
    ]) {
      expect(isBuildVersion(version)).toBe(false);
    }
  });
});

describe("setBuildVersionContents", () => {
  const files = fixtureFiles();

  it("stamps an rc prerelease into all four version files", () => {
    const next = setBuildVersionContents(files, "0.0.25-rc.1");
    expect(JSON.parse(next.tauriConf).version).toBe("0.0.25-rc.1");
    expect(JSON.parse(next.packageJson).version).toBe("0.0.25-rc.1");
    expect(next.cargoToml).toContain('version = "0.0.25-rc.1"');
    expect(next.cargoLock).toContain('version = "0.0.25-rc.1"');
  });

  it("stamps a clean stable version", () => {
    const next = setBuildVersionContents(files, "0.0.25");
    expect(Object.values(next).every((contents) => contents.includes("0.0.25"))).toBe(true);
  });

  it("stamps historical release sources whose Cargo.lock has only the legacy package", () => {
    const legacyFiles = {
      ...files,
      cargoLock: files.cargoLock.replace('name = "clovy"', 'name = "os-june"'),
    };
    const next = setBuildVersionContents(legacyFiles, "0.0.25");
    expect(next.cargoLock).toContain('name = "os-june"\nversion = "0.0.25"');
  });

  it("does not enforce monotonic increase (rc sorts below its base)", () => {
    // 0.0.24-rc.1 < 0.0.24, which bump-version.mjs would reject; here it's fine.
    const next = setBuildVersionContents(files, "0.0.24-rc.1");
    expect(JSON.parse(next.packageJson).version).toBe("0.0.24-rc.1");
  });

  it("throws on an invalid version rather than writing garbage", () => {
    expect(() => setBuildVersionContents(files, "1.2")).toThrow();
  });

  it("rejects pre-existing drift before transforming any file", () => {
    const drifted = { ...files, cargoLock: files.cargoLock.replace("0.0.24", "0.0.23") };
    expect(() => setBuildVersionContents(drifted, "0.0.25-rc.1")).toThrow("Version drift");
  });
});

describe("set-build-version CLI", () => {
  it("checks four-file agreement without writing", () => {
    const { root, files } = writeFixture();
    try {
      execFileSync(process.execPath, [scriptPath, "--check", "0.0.24"], { cwd: root });
      expect(readFixture(root)).toEqual(files);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("fails check mode on an expected-version mismatch without writing", () => {
    const { root, files } = writeFixture();
    try {
      const result = spawnSync(process.execPath, [scriptPath, "--check", "0.0.25"], {
        cwd: root,
        encoding: "utf8",
      });
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("Expected version 0.0.25, found agreed version 0.0.24");
      expect(readFixture(root)).toEqual(files);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("fails check mode on drift without writing", () => {
    const { root } = writeFixture();
    const cargoLockPath = join(root, "src-tauri", "Cargo.lock");
    writeFileSync(cargoLockPath, readFileSync(cargoLockPath, "utf8").replace("0.0.24", "0.0.23"));
    const before = readFixture(root);
    try {
      const result = spawnSync(process.execPath, [scriptPath, "--check", "0.0.24"], {
        cwd: root,
        encoding: "utf8",
      });
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("Version drift");
      expect(readFixture(root)).toEqual(before);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    "0.0.25",
    "0.0.25-rc.1",
  ])("directly stamps %s and leaves locked Cargo metadata valid", (version) => {
    const { root } = writeFixture();
    try {
      execFileSync(process.execPath, [scriptPath, version], { cwd: root });
      const lockAfterStamp = readFileSync(join(root, "src-tauri", "Cargo.lock"), "utf8");
      const metadata = execFileSync(
        "cargo",
        [
          "metadata",
          "--manifest-path",
          "src-tauri/Cargo.toml",
          "--locked",
          "--no-deps",
          "--format-version",
          "1",
        ],
        { cwd: root, encoding: "utf8" },
      );
      expect(JSON.parse(metadata).packages[0].version).toBe(version);
      expect(readFileSync(join(root, "src-tauri", "Cargo.lock"), "utf8")).toBe(lockAfterStamp);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("stamps a historical os-june package and preserves locked Cargo metadata", () => {
    const version = "0.0.25";
    const { root } = writeFixture("0.0.24", "os-june");
    try {
      execFileSync(process.execPath, [scriptPath, version], { cwd: root });
      const lockAfterStamp = readFileSync(join(root, "src-tauri", "Cargo.lock"), "utf8");
      const metadata = JSON.parse(
        execFileSync(
          "cargo",
          [
            "metadata",
            "--manifest-path",
            "src-tauri/Cargo.toml",
            "--locked",
            "--no-deps",
            "--format-version",
            "1",
          ],
          { cwd: root, encoding: "utf8" },
        ),
      );

      expect(metadata.packages).toHaveLength(1);
      expect(metadata.packages[0]).toMatchObject({ name: "os-june", version });
      expect(lockAfterStamp).toContain(`name = "os-june"\nversion = "${version}"`);
      expect(readFileSync(join(root, "src-tauri", "Cargo.lock"), "utf8")).toBe(lockAfterStamp);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("compareBuildVersion", () => {
  it("orders rc iterations of the same base", () => {
    expect(compareBuildVersion("0.0.25-rc.2", "0.0.25-rc.1")).toBe(1);
    expect(compareBuildVersion("0.0.25-rc.1", "0.0.25-rc.2")).toBe(-1);
    expect(compareBuildVersion("0.0.25-rc.10", "0.0.25-rc.9")).toBe(1);
  });

  it("treats a clean base as greater than its prereleases", () => {
    expect(compareBuildVersion("0.0.25", "0.0.25-rc.9")).toBe(1);
    expect(compareBuildVersion("0.0.25-rc.9", "0.0.25")).toBe(-1);
  });

  it("orders across bases before rc number", () => {
    expect(compareBuildVersion("0.0.26-rc.1", "0.0.25-rc.9")).toBe(1);
    // A lower base still loses even with a higher rc number.
    expect(compareBuildVersion("0.0.25-rc.9", "0.0.26-rc.1")).toBe(-1);
  });

  it("reports equality for identical versions", () => {
    expect(compareBuildVersion("0.0.25-rc.2", "0.0.25-rc.2")).toBe(0);
  });

  it("throws on an unparseable operand", () => {
    expect(() => compareBuildVersion("0.0.25-rc.2", "garbage")).toThrow();
  });
});
