import { describe, expect, it } from "vitest";
import {
  bumpVersionContents,
  currentVersionFromCargoLock,
  currentVersionFromCargoToml,
  readCurrentVersion,
  validateRequestedVersion,
} from "../../scripts/bump-version.mjs";

const cargoLock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "dependency"
version = "9.8.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "unchanged"

[[package]]
name = "os-june"
version = "0.1.0"
dependencies = [
 "dependency",
]
`;

const files = {
  tauriConf: '{\n  "productName": "June",\n  "version": "0.1.0"\n}\n',
  cargoToml: '[package]\nname = "os-june"\nversion = "0.1.0"\n',
  cargoLock,
  packageJson: '{\n  "name": "os-june",\n  "version": "0.1.0"\n}\n',
};

describe("validateRequestedVersion", () => {
  it("accepts a valid higher version", () => {
    expect(validateRequestedVersion("0.1.0", "0.2.0")).toEqual({ ok: true });
  });

  it("rejects non-semver values", () => {
    expect(validateRequestedVersion("0.1.0", "0.2")).toEqual({
      ok: false,
      reason: 'Requested version "0.2" is not valid semver (expected X.Y.Z).',
    });
  });

  it("rejects equal and lower versions", () => {
    expect(validateRequestedVersion("0.1.0", "0.1.0").ok).toBe(false);
    expect(validateRequestedVersion("0.1.0", "0.0.9").ok).toBe(false);
  });

  it("rejects malformed versions", () => {
    expect(validateRequestedVersion("0.1.0", "01.2.3").ok).toBe(false);
    expect(validateRequestedVersion("0.1.0", "1.2.3-beta.1").ok).toBe(false);
  });
});

describe("bumpVersionContents", () => {
  it("updates all version-bearing files", () => {
    const next = bumpVersionContents(files, "0.2.0");

    expect(JSON.parse(next.tauriConf).version).toBe("0.2.0");
    expect(next.cargoToml).toContain('version = "0.2.0"');
    expect(currentVersionFromCargoLock(next.cargoLock)).toBe("0.2.0");
    expect(JSON.parse(next.packageJson).version).toBe("0.2.0");
  });

  it("preserves every unrelated Cargo.lock byte", () => {
    const next = bumpVersionContents(files, "0.2.0");
    expect(next.cargoLock).toBe(cargoLock.replace('version = "0.1.0"', 'version = "0.2.0"'));
  });

  it("preserves Cargo.lock CRLF endings and final-newline state", () => {
    const crlfLock = cargoLock.replaceAll("\n", "\r\n").trimEnd();
    const next = bumpVersionContents({ ...files, cargoLock: crlfLock }, "0.2.0");
    expect(next.cargoLock).toBe(crlfLock.replace('version = "0.1.0"', 'version = "0.2.0"'));
  });
});

describe("readCurrentVersion", () => {
  it("returns the shared version when all four files agree", () => {
    expect(readCurrentVersion(files)).toEqual({ ok: true, version: "0.1.0" });
  });

  it.each([
    ["package.json", { packageJson: files.packageJson.replace("0.1.0", "0.1.1") }],
    ["tauri.conf.json", { tauriConf: files.tauriConf.replace("0.1.0", "0.1.1") }],
    ["Cargo.toml", { cargoToml: files.cargoToml.replace("0.1.0", "0.1.1") }],
    [
      "Cargo.lock",
      { cargoLock: files.cargoLock.replace('version = "0.1.0"', 'version = "0.1.1"') },
    ],
  ])("rejects drift in %s", (_name, change) => {
    expect(readCurrentVersion({ ...files, ...change }).ok).toBe(false);
  });
});

describe("currentVersionFromCargoToml", () => {
  it("reads the [package] version, not another table's version", () => {
    const cargo =
      '[workspace.package]\nversion = "9.9.9"\n\n[package]\nname = "os-june"\nversion = "0.1.0"\n';
    expect(currentVersionFromCargoToml(cargo)).toBe("0.1.0");
  });

  it("bumps the [package] version while leaving other tables untouched", () => {
    const cargo =
      '[workspace.package]\nversion = "9.9.9"\n\n[package]\nname = "os-june"\nversion = "0.1.0"\n';
    const next = bumpVersionContents({ ...files, cargoToml: cargo }, "0.2.0");
    expect(next.cargoToml).toContain('[workspace.package]\nversion = "9.9.9"');
    expect(next.cargoToml).toContain('[package]\nname = "os-june"\nversion = "0.2.0"');
  });
});

describe("currentVersionFromCargoLock", () => {
  it("reads the root package version rather than a dependency version", () => {
    expect(currentVersionFromCargoLock(cargoLock)).toBe("0.1.0");
  });

  it("fails when the os-june package is missing", () => {
    expect(() =>
      currentVersionFromCargoLock(cargoLock.replace('name = "os-june"', 'name = "other"')),
    ).toThrow("Could not find");
  });

  it("fails when the os-june package is duplicated", () => {
    const duplicate = `${cargoLock}\n[[package]]\nname = "os-june"\nversion = "0.1.0"\n`;
    expect(() => currentVersionFromCargoLock(duplicate)).toThrow("multiple");
  });

  it.each([
    ["missing", cargoLock.replace('version = "0.1.0"\n', "")],
    ["malformed", cargoLock.replace('version = "0.1.0"', "version = 0.1.0")],
    ["duplicate", cargoLock.replace('version = "0.1.0"', 'version = "0.1.0"\nversion = "0.1.0"')],
  ])("fails on a %s os-june version field", (_name, lock) => {
    expect(() => currentVersionFromCargoLock(lock)).toThrow();
  });

  it.each(["source", "checksum"])("rejects an os-june package with a %s field", (field) => {
    const lock = cargoLock.replace(
      'name = "os-june"\n',
      `name = "os-june"\n${field} = "registry identity"\n`,
    );
    expect(() => currentVersionFromCargoLock(lock)).toThrow(`contains a ${field} field`);
  });
});
